### ISSUE TITLE
VHDCI carrier assembly variant

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/VHDCI_Carrier#1]
@hartytp What should be default assembly variant for backplane connector? DC jack or DIN connector compatible with Kasli mini-backplane?

**Comment by hartytp** [comment]
At this point, I'd prefer to scrap the BP connector entirely and just keep a barel connector or two. After all, IIRC, we've agreed to scrap it on Kasli. Any objections @jordens ?

**Comment by jordens** [comment]
IMHO scrap it but keep an internal power connector (barrel FWIW) in addition to the external one.

**Comment by hartytp** [comment]
:+1:
