### ISSUE TITLE
General purpose IDC <-> VHDCI adapter

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/VHDCI_Carrier#2]
To make the VHDCI Carrier being discoverable by Kasli we need to reverse the I2C switch.
Output port 1 (I2C0) must be connected to the VHDCI I2C port.
The easiest way of doing this is to keep the I2C switch in reset state and short input with output port.
In this way Kasli on EEM0 will control VHDCI0 and on EEM4 will control VHDCI1.
Mode selection (standard operation vs Kasli mode) will be done by DIP switch.
@hartytp is that OK for you?

**Comment by hartytp** [comment]
@gkasprow That sounds like a sensible way of doing this, but I'd value feedback from @jordens or @sbourdeauducq who will have a better feeling for the best way to interface this with ARTIQ...

**Comment by jordens** [comment]
Good. That looks like the right way to do it to me. If possible I'd have the eems on the first four i2c ports and the eeprom on the last though.

**Comment by gkasprow** [comment]
I can change it, but take into account that we have already some amount of v1.1 around...
